# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(614, 93)
        self.btn = QtWidgets.QPushButton(parent=Form)
        self.btn.setGeometry(QtCore.QRect(0, 50, 61, 41))
        self.btn.setObjectName("btn")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.edit2 = QtWidgets.QLineEdit(parent=Form)
        self.edit2.setGeometry(QtCore.QRect(100, 20, 101, 22))
        self.edit2.setObjectName("edit2")
        self.edit3 = QtWidgets.QLineEdit(parent=Form)
        self.edit3.setGeometry(QtCore.QRect(200, 20, 101, 22))
        self.edit3.setObjectName("edit3")
        self.edit4 = QtWidgets.QLineEdit(parent=Form)
        self.edit4.setGeometry(QtCore.QRect(300, 20, 101, 22))
        self.edit4.setObjectName("edit4")
        self.edit5 = QtWidgets.QLineEdit(parent=Form)
        self.edit5.setGeometry(QtCore.QRect(400, 20, 101, 22))
        self.edit5.setObjectName("edit5")
        self.edit6 = QtWidgets.QLineEdit(parent=Form)
        self.edit6.setGeometry(QtCore.QRect(500, 20, 101, 22))
        self.edit6.setObjectName("edit6")
        self.edit1 = QtWidgets.QLineEdit(parent=Form)
        self.edit1.setGeometry(QtCore.QRect(0, 20, 101, 22))
        self.edit1.setObjectName("edit1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn.setText(_translate("Form", "text"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Сорт"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Обжарка"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Молотый/в зернах"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Вкус"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Цена"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Обьем"))
